# gitleaks-config.toml
[[rules]]
  id = "aws_access_key_id"
  description = "AWS Access Key ID"
  regex = '''[A-Z0-9]{20}'''

[[rules]]
  id = "api_key"
  description = "API Key"
  regex = '''[A-Za-z0-9]{32,}'''

[[rules]]
  id = "private_key"
  description = "Private Key"
  regex = '''BEGIN\sPRIVATE\sKEY'''

[[rules]]
  id = "password"
  description = "Password"
  regex = '''(password|pwd)\s*[:=]\s*\S+'''

[[rules]]
  id = "jwt_token"
  description = "JWT Token"
  regex = '''eyJ[[:alnum:]-_]+.[[:alnum:]-_]+.[[:alnum:]-_]+'''

[[rules]]
  id = "oauth_token"
  description = "OAuth Token"
  regex = '''oauth_token\s*[:=]\s*\S+'''

  [[rules.Entropies]]
      Min = "4.3"
      Max = "8.0"
