name: Gitleaks Scan and Notify

on:
  push:
    branches:
      - main  # Replace with your repository's main branch

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x  # Replace with your desired Go version

    - name: Install Gitleaks
      run: go get -u github.com/zricethezav/gitleaks

    - name: Run Gitleaks with Custom Configuration
      run: gitleaks --path=./ --redact --config=gitleaks-config.toml --report=gitleaks-report.json

    - name: Create GitHub Issue
      if: failure()  # Create an issue only if there was a failure (secrets detected)
      run: |
        ISSUE_TITLE="Secrets Detected in Code"
        ISSUE_BODY="Secrets were detected in the code. Please review and take necessary action."
        GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        curl -X POST "https://api.github.com/repos/${{ github.repository }}/issues" \
          -H "Authorization: token $GITHUB_TOKEN" \
          -d "{\"title\":\"$ISSUE_TITLE\",\"body\":\"$ISSUE_BODY\"}"

  
